# version 行は削除（警告防止）
services:
  php:
    build:
      context: ./docker/php        # ← ここを直す（Dockerfile のフォルダ）
      dockerfile: Dockerfile       # ← ファイル名
    working_dir: /var/www          # ← あなたの Dockerfile の WORKDIR と合わせる
    volumes:
      - ./src:/var/www             # ← Laravel のコードをマウント
    depends_on:
      - mysql
      - mailhog

  nginx:
    image: nginx:1.21.1
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www
    depends_on:
      - php

  mysql:
    image: mysql:8.0.26
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: laravel_user
      PMA_PASSWORD: laravel_pass
    depends_on:
      - mysql
    ports:
      - "8080:80"

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025"   # Web UI
      - "1025:1025"   # SMTP
